CREATE TABLE TODO (
    ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512) NULL,
    DONE BOOLEAN,
    USERID VARCHAR(12) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES users(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);